name: Unit Tests # name of the test

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
        with:
            path: source 

      - name: Install Dependencies
        working-directory: ./source
        run: npm install
        
      - name: Unit Test
        working-directory: ./source
        run: npm test ./calendar.test.js # the actual testing line
